<a href="https://colab.research.google.com/github/creamcheesesteak/test_deeplearning/blob/master/dff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy

# sigmoid

In [2]:
a = tf.constant([-2, -1.0, 0.0, 1.0, 20], dtype = tf.float32)

In [5]:
a, type(a)

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1., 20.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [3]:
b = tf.keras.activations.sigmoid(a) 

In [4]:
b.numpy()

array([0.11920291, 0.26894143, 0.5       , 0.7310586 , 1.        ],
      dtype=float32)

# softmax

In [9]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.61820215, -0.31310037,  0.9484779 ]], dtype=float32)>

In [10]:
outputs = tf.keras.activations.softmax(inputs)

In [11]:
outputs.numpy()

array([[0.13990945, 0.18982397, 0.67026657]], dtype=float32)