<a href="https://colab.research.google.com/github/creamcheesesteak/test_deeplearning/blob/master/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [5]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [6]:
df_load = pd.read_sql_query('select * from iris_resource', connect)

In [7]:
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [9]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [13]:
import numpy as np

In [14]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [10]:
import tensorflow as tf

In [11]:
model = tf.keras.Sequential()

In [20]:
model.add(tf.keras.Input(shape=(4, ))) # input layer
model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(24, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(3, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='mse', metrics=['acc']) # gadget 

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 24)                1560      
_________________________________________________________________
input_2 (InputLayer)         multiple                  0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                1600      
_________________________________________________________________
dense_3 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 75        
_________________________________________________________________
input_3 (InputLayer)         multiple                  0

In [22]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3) # 학습

Epoch 1/50
4/4 [==============================] - 1s 65ms/step - loss: 0.3969 - acc: 0.1905 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3968 - acc: 0.4762 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3968 - acc: 0.5143 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3968 - acc: 0.1714 - val_loss: 2.7778 - val_acc: 1.0000
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3968 - acc: 0.0476 - val_loss: 2.7778 - val_acc: 0.0222
Epoch 6/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3968 - acc: 0.5333 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3968 - acc: 0.4762 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3968 - ac

# Evaluation

In [23]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 2ms/step - loss: 1.1111 - acc: 0.2800


[1.111111044883728, 0.2800000011920929]

# service

In [24]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [26]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33334416, 0.33331066, 0.3333452 ]], dtype=float32)

In [27]:
import numpy as np
np.argmax(pred)

2