<a href="https://colab.research.google.com/github/creamcheesesteak/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
len(code2idx)

14

In [5]:
code2idx['g8']

11

In [6]:
range(len(note_seq)-4) # [4, 8, 12 ...]

range(0, 50)

In [7]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
    # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [8]:
import numpy as np

In [9]:
datasets = np.array(dataset)

In [10]:
x_train = datasets[:,0:3]
x_train.shape, # x_train

((50, 3),)

In [11]:
y_train = datasets[:,3]
y_train.shape, # y_train

((50,),)

In [12]:
x_train = x_train / 13  # len(code2dix)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [13]:
import tensorflow as tf
model = tf.keras.models.Sequential()

In [14]:
x_train.shape # --> tensorflow type(tensor)  (50,3,1)
x_train[2]

array([0.15384615, 0.76923077, 0.61538462])

In [15]:
X_train = np.reshape(x_train, (50, 3, 1))
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [16]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [17]:
model.add(tf.keras.Input(shape=(3,1)))
model.add(tf.keras.layers.LSTM(128)) # input layer, column의 값을 input으로
# LSTM(batch_size, timesteps, input_dim) -> (row, cols, )
# model.add() # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [18]:
hist = model.fit(X_train, y_train, epochs=2, batch_size=1)

Epoch 1/2
50/50 [==============================] - 1s 2ms/step - loss: 2.4821 - accuracy: 0.2800
Epoch 2/2
50/50 [==============================] - 0s 2ms/step - loss: 2.1227 - accuracy: 0.3400


In [19]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 1.9444 - accuracy: 0.3400


[1.9444409608840942, 0.3400000035762787]